### ISSUE TITLE
Does not seem to work with physbone component on mesh

### ISSUE THREAD

**Issue by WentTheFox** [RichiCoder1/VrcOscLeash#1]
Hi, I tried the module yesterday but unfortunately it did not work for my leash setup. I'm using a Valve Index with its knuckles controllers, not sure if that matters. On the avatar itself I have the following layout:

<details open>
<summary>Collar + leash root</summary>

(attached to the neck bone via VRCFury)

> <details open>
> <summary>Armature</summary>
>
>    > <details open>
>    > <summary>Collar</summary>
>    >
>    >    > <details open>
>    >    > <summary>Leash1</summary>
>    >    > (this is the first bone of the leash mesh)
>    >    >
>    >    >   > <details open>
>    >    >   >  <summary>…</summary>
>    >    >   > (bones Leash2 through Leash7 are nested in each other, omitted for brevity)
>    >    >   >
>    >    >   >    > <details open>
>    >    >   >    > <summary>Leash8</summary>
>    >    >   >    > (this is the leaf bone of the leash)
>    >    >   >    > </details>
>    >    >   >
>    >    >   > </details>
>    >    >
>    >    > </details>
>    >
>    > </details>
>
> </details>
> <details open>
> <summary>Collar</summary>
> (this is just a mesh)
> </details>
> <details open>
> <summary>Leash</summary>
> (this is also a mesh, but it's where my physbone script is)
> </details>

</details>

It's set up like this because I have a toggle on the Leash mesh that enables/disables it and it's convenient to have the physbone on it as well.

I'm wondering if this is something that this script could support, I have a feeling the reason why it broke was because the physbone is on the Leash mesh instead of the Leash1 bone, but I wanted to ask here first before doing any further testing to see if I should rethink this setup entirely.

I have a feeling the script expects the physbone script to be on the Leash1 bone, but because Leash8 is not a child of the physvbone node (which outside the armature) I am assuming the calculation breaks somehow. Documentation regarding the expected setup would certainly be appreciated as well, it could have helped avoid the issue, since I'm not sure how this module is supposed to work.

**Comment by RichiCoder1** [comment]
@DJDavid98 Apologies, just seeing this issue! I think there's an issue with the Leash logic I need to resolve.

> I have a feeling the script expects the physbone script to be on the Leash1 bone, but because Leash8 is not a child of the physvbone node (which outside the armature) I am assuming the calculation breaks somehow. Documentation regarding the expected setup would certainly be appreciated as well, it could have helped avoid the issue, since I'm not sure how this module is supposed to work.

Interesting, I'm not entirely sure I follow entirely, but I think (once I fix the above issue), this should be supported. What does the debug output of the component report after you have it setup?

**Comment by RichiCoder1** [comment]
FYI I released a new version of the program and component which might resolve any issues

**Comment by WentTheFox** [comment]
I've just returned from a trip abroad, I'll check the latest version ASAP

**Comment by WentTheFox** [comment]
I had the chance to try the updated module and prefab today, unfortunately it still does not seem to work. Is there a chance you could share some screenshots of an ideal setup that does work, including the object hierarchy and where each component (physbone and leash) should be placed?
